name: dart_tree
version: 1.0.0
environment:
  sdk: ^3.9.2

dependencies:
  args: ^2.4.2
  code_builder: ^4.11.0
  collection: ^1.19.1
  copy_with_extension: ^11.0.0
  equatable: ^2.0.7
  json_annotation: ^4.9.0
  path: ^1.9.0
  recase: ^4.1.0
  uuid: ^4.5.2
  yaml: ^3.1.2

dev_dependencies:
  build_runner: ^2.4.0
  copy_with_extension_gen: ^11.0.0
  dart_tree_gen:
    path: ../dart_tree_gen
  json_serializable: ^6.9.0
  test: ^1.24.0
